# Generated by Django 3.0.4 on 2020-03-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowedbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='phone_number',
        ),
    ]
